---
language: go
sudo: false
go:
  - "1.14"
  - tip
branches:
  # don't build pull requests twice
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
jobs:
  fast_finish: true
  allow_failures:
    - go: tip
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
script:
  - make coverage
  - make lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
