---
language: go
sudo: false
go:
  - "1.14"
  - tip
env:
  global:
    - GO111MODULE=on
branches:
  # don't build pull requests twice
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
script:
  - make coverage
  - make lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
